### ISSUE TITLE
Tag/Release for version 1.2

### ISSUE THREAD

**Issue by ratijas** [hwmaier/asciidoc-mscgen-filter#3]
Versions 1.0 and 1.1 are properly tagged, and GitHub has generated appropriate release pages for them.  However version 1.2 is only ever specified in README, but neither tagged nor added to the Releases page.

Please, consider pushing git tag for `1.2`.

**Comment by ratijas** [comment]
Ping, @hwmaier

**Comment by hwmaier** [comment]
Done.

**Comment by ratijas** [comment]
Thank you!
